name: anttec_movil
description: "AplicaciÃ³n mÃ³vil ANTTEC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4 

dependencies:
  flutter:
    sdk: flutter

  # --- ğŸ§  INTELIGENCIA ARTIFICIAL ---
  langchain: ^0.8.0
  langchain_mistralai: ^0.3.1+1

  # --- ğŸ¨ DISEÃ‘O Y FORMATO ---
  flutter_markdown: ^0.7.1
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2872.1
  cached_network_image: ^3.3.1

  # --- ğŸ§­ NAVEGACIÃ“N Y LÃ“GICA ---
  go_router: ^16.2.1
  dio: ^5.9.0
  provider: ^6.1.5+1

  # --- ğŸ’¾ ALMACENAMIENTO Y DATOS ---
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  connectivity_plus: ^6.0.4

  # --- ğŸ›  UTILIDADES ---
  form_field_validator: ^1.1.0
  mobile_scanner: ^6.0.2

  # --- ğŸ–¨ï¸ IMPRESIÃ“N Y PERIFÃ‰RICOS (MÃ“DULO VENTAS) ---
  # Genera los comandos ESC/POS (negritas, cortes, texto)
  esc_pos_utils_plus: ^2.0.3 
  
  # Necesario para procesar imÃ¡genes internamente
  image: ^4.0.17
  
  # Para manejar la impresora Bluetooth (VersiÃ³n estable)
  print_bluetooth_thermal: ^1.1.9
  
  # Para pedir permisos en tiempo de ejecuciÃ³n
  permission_handler: ^11.3.0

  # âœ… VITAL: Para escanear la red WiFi y encontrar ticketeras IP
  network_info_plus: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/